apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: login-deploy
  template:
    metadata:
      labels:
        run: login-deploy
    spec:
      containers:
      - image: doinsin/my-login-app:v1
        name: test
        ports:
        - containerPort: 80
